### ISSUE TITLE
Frontend support for using region fieldtype or country fieldtype in a form

### ISSUE THREAD

**Issue by carolineferraby** [kadegray/statamic-country-and-region-fieldtypes#5]
I am trying to use the region fieldtype and the country fieldtype for two fields in a form, specifically user:register_form (https://statamic.dev/tags/user-register_form#overview) and user:profile_form. However, I am having trouble getting the fields to register correctly in my antlers template. Instead of showing the country field as plain text with {{ country }}, I want to show the country field as a select form field with all the countries as options. And the same goes for the region field.

The idea is that when a new user registers on the site, they are taken to a registration form, and they can select with region and country they are from, and then submit the form with that information.

A very simplified version of my antlers template looks something like this, where region and country are two of the fields in the form:
```
{{ user:register_form }}
    {{ fields }}
        <label>{{ display }}</label>
        {{ field }}
    {{ /fields }}
{{ /user:register_form }}
```

Following the directions here, https://statamic.dev/tags/form-create#prerendered-field-html, I have editable templates snippets for each form fieldtype. For the country form fieldtype, there is no snippet that exists, so I had to add one (views/vendor/statamic/forms/fields/country.antlers.html file). That file will be rendered for the country field, in place of the {{ field }} variable (the files seem to be rendered based on the pattern {type}.antlers.html).

I now have to write the html for the country.antlers.html file (and region.antlers.html file). I assume I want to use a select html tag with nested options, but I don't know how to pull in the data for each of the options from the country (or region) field. Can you please help me get both region and country fields rendering on the frontend for a form? And if this is not supported, please let me know, or even better, please provide an update/documentation that supports it. Thanks.

**Comment by kadegray** [comment]
You're right, this would be a good thing to have. Unfortunately this addon does not currently have form fields for country or region. Since the main challenge is getting data consistent with the addon (countries, regions) into a select and I think it is best to let developers control their html. I have explored adding tags that would assist in generating select options for fields they might want to create.

Thank you for creating this issue I will explore it further and hopefully be able to provide a solution for this.

**Comment by carolineferraby** [comment]
Thank you for looking into this. Would you be able to give a timeframe/ETA for a solution/update?

**Comment by kadegray** [comment]
Hi @carolineferraby, I've pushed an update in 1.2.0 that adds a tag that you can make use of. To update use: `composer update kadegray/statamic-country-and-region-fieldtypes`.

See this documentation: https://github.com/kadegray/statamic-country-and-region-fieldtypes#countries_and_regions-tag

Please let me know how you go.

**Comment by carolineferraby** [comment]
@kadegray, thank you for the update. I updated the addon and read the documentation. I then copied and pasted the select markup for the country and region field, which created select fields as expected. On submitting the form, the country and region data saves correctly in ISO format, and when outputting {{ country }} and {{ region }} into an email, the data outputs correctly. All of this is a great improvement. There is just one thing not working quite right. In my form, I have region listed first before country, with the default country set to 'US'. However, if a user selects a different country, I want the region options to be updated. I assume that this is what the JavaScript is for. I put the JavaScript in the same antlers file as the country select field, and tried filling out the form. However, when I go to change the country field, I get this error in my console: 'Uncaught (in promise) SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data'. I tried editing the JavaScript myself to resolve the JSON syntax error (removing the trailing commas), but the error did not go away, and the region options still aren't updating. I'm not sure if I need to update the filepath in "/countries_and_regions/${regionCode}/regions"? Let me know how I can resolve this error.

**Comment by kadegray** [comment]
@carolineferraby I noticed I got naming wrong in that example <script> block of the documentation. I've pushed changes to that. Anyway this is unrelated to your error. But feel free to copy and paste the new example in. (https://github.com/kadegray/statamic-country-and-region-fieldtypes/commit/ce0c9b27a8961c87ae5e5083851513403df5e97e) (https://github.com/kadegray/statamic-country-and-region-fieldtypes#endpoint-countries_and_regionscountrycoderegions)

If this error is from the example code it might from `const regions = await response.json();` which is probably calling JSON.parse on the response. Which suggests that the response is not json. But its strange because it usually says something about it not being valid json.

1. Open up DevTools. (https://developer.chrome.com/docs/devtools/open/)
2. Have a look at Network activity. (https://developer.chrome.com/docs/devtools/network/)
3. Filter the network activity for XHR and you should see a request to /regions. Click on it.
4. Look at the responses tab for that request and see what is in there, it might be an error instead.

I haven't been able to replicate the error. But please:
1. copy and paste the whole error here.
2. provide the full path of the regions request url. (you don't have to include the domain)
3. provide the html of the selects.

It might have something to do with the value on the options of the country select.

**Comment by carolineferraby** [comment]
@kadegray, I updated the <script> block according to your latest documentation, thanks. As for the error, I was originally testing in Firefox, but I can see that you're more familiar with Chrome. This is the error I get in Chrome's console when I open the page with my form and change the country field: `Uncaught (in promise) SyntaxError: Unexpected token '<', "<!doctype "... is not valid JSON _await (async)_ onchange`. Same error, just worded differently between browsers.

When I go to DevTools > Network > regions > Response tab, I get this solo message "Failed to load response data: No content available because this request was redirected." The regions request URL is `https://domain.com/countries_and_regions/ZA/regions`... though I get this same error no matter which country I choose. Same result for `https://domain.com/countries_and_regions/SE/regions`. Lastly, the html of the selects...

For some context, I followed this documentation [https://statamic.dev/tags/form-create#prerendered-field-html](https://statamic.dev/tags/form-create#prerendered-field-html), and ran the php command to create override files for the various fields. I have since created _country.antlers.html and _region.antlers.html (in the views/vendor/statamic/forms/fields folder), and used the existing select markup, plus what you gave me, to come up with the following html:

_country.antlers.html
```
<select 
    id="country"
    name="{{ handle }}{{ multiple ?= "[]" }}"
    onchange="reloadRegions()"
    {{ if js_driver }}{{ js_attributes }}{{ /if }}
    {{ if multiple }}multiple{{ /if }}
    {{ if validate|contains:required }}required{{ /if }}
    {{ if error }}aria-invalid="true" aria-describedby="{{ handle }}-error"{{ /if }} 
>
    {{ unless multiple }}
        <option value disabled>
            {{ if placeholder }}
                {{ placeholder }}
            {{ else }}
                {{ trans key="Please select..." }}
            {{ /if }}
        </option>
    {{ /unless }}
    {{ countries_and_regions:countries default="US" }}
        <option value="{{ isoCode }}" {{ selected }}>
            {{ countryName }}
        </option>
    {{ /countries_and_regions:countries }}
</select>
<script>...</script>
```
_region.antlers.html
```
<select 
    id="region"
    name="{{ handle }}{{ multiple ?= "[]" }}"
    {{ if js_driver }}{{ js_attributes }}{{ /if }}
    {{ if multiple }}multiple{{ /if }}
    {{ if validate|contains:required }}required{{ /if }}
    {{ if error }}aria-invalid="true" aria-describedby="{{ handle }}-error"{{ /if }}
>
    {{ unless multiple }}
        <option value selected disabled>
            {{ if placeholder }}
                {{ placeholder }}
            {{ else }}
                {{ trans key="Please select..." }}
            {{ /if }}
        </option>
    {{ /unless }}
    {{ countries_and_regions:regions country="US" }}
        <option value="{{ isoCode }}">
            {{ regionName }}
        </option>
    {{ /countries_and_regions:regions }}
</select>
```
I hope this is helpful. I did test with and without the {{ unless }} block, and it didn't have an effect on the error.

**Comment by kadegray** [comment]
@carolineferraby  I don't know about the 'request was redirected' part. But please try running `php artisan route:clear`. If you have run `php artisan route:cache` in the past this might be the cause, because there is a new route in these recent changes.
